apiVersion: kibana.k8s.elastic.co/v1 
kind: Kibana 
metadata: 
  name: kibana 
spec: 
  version: 8.15.0
  count: 1 
  elasticsearchRef: 
    name: elastic 
  http:
    service:
      spec:
        type: NodePort
        ports:
         - name: https
           nodePort: 31112
           port: 5601
           protocol: TCP
           targetPort: 5601
  config:
    xpack.fleet.packages:
    - name: apm
      version: latest