apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data: # This is bad practice, don't do this. C'mon.
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: bankaudit
  PGDATA: /var/lib/postgresql/data/pgdata
  RABBITMQ_USER: guest
  RABBITMQ_PASS: guest

