logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

cloud:
  aws:
    s3:
      enabled: false

generator:
  rate: 90_000
scan:
  rate: 30_000

parse:
  local:

    pattern: '*.batch'
  s3:
    bucket: ${S3_BUCKET_URL}
    pattern: ${S3_RESOURCE_PATTERN}

spring:
  sql:
    init:
      mode: always
  application:
    name: bankaudit-batch
  batch:
    jdbc:
      initialize-schema: always
  reactor:
    context-propagation: auto
  rabbitmq:
    exchange: bankaudit
    queue:
      pending:
        all: pending
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    template:
      observation-enabled: true
    listener:
      stream:
        observation-enabled: true
      direct:
        observation-enabled: true
      simple:
        observation-enabled: true
  datasource:
    url: "jdbc:${AUDIT_DB_URL}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

otel:
  propagators: "tracecontext,baggage"
  resource:
    attributes:
      deployment.environment: dev
      service:
        name: batch
        namespace: com.jdkendall.bankaudit
        node:
          name: ${POD_NAME:default}
  exporter:
    otlp:
      metrics:
        endpoint: ${OTEL_ENDPOINT}
        headers:
          Authorization: Bearer ${OTEL_API_KEY}
      endpoint: ${OTEL_ENDPOINT}
      headers:
        Authorization: Bearer ${OTEL_API_KEY}
  instrumentation:
    micrometer:
      enabled: true
    rabbitmq:
      experimental-span-attributes: true

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: ${OTEL_ENDPOINT}
        headers:
          Authorization: Bearer ${OTEL_API_KEY}
#    tracing:
#      endpoint: ${OTEL_ENDPOINT}
#      headers:
#        Authorization: Bearer ${OTEL_API_KEY}
