receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: 'localhost:4317'
      http: 
        endpoint: 'localhost:55681'

processors:
  batch: null

exporters:
  logging:
    loglevel: info
  elastic:
    apm_server_url: "http://apm-server:8200"
    secret_token: ""  # Set this if you are using a secret token
    # You might need additional configuration based on your APM server setup

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elastic, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]

